name: php-environment

services:
  webserver:
    container_name: httpd
    build:
      context: .docker/
      dockerfile: apache.Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/usr/local/apache2/htdocs/
    networks:
      - php
    depends_on:
      php:
        condition: service_healthy
        restart: true

  php:
    container_name: php
    build:
      context: .docker/
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - .:/usr/local/apache2/htdocs/
    networks:
      - php
    healthcheck:
      test: ["CMD", "php", "--version"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  database:
    image: mysql:8.0.43
    container_name: mysql
    restart: always
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: qwr34r34
    ports:
      - 3306:3306
    networks:
      - php
    healthcheck:
      test: ["CMD", "mysql"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    ports:
      - 3000:80
    networks:
      - php
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      database:
        condition: service_healthy
        restart: true


volumes:
  mysql: {}

networks:
  php:
    driver: bridge
