name: php-environment

services:
  webserver:
    container_name: httpd
    build:
      context: .docker/
      dockerfile: apache.Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/usr/local/apache2/htdocs
      - .docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - php
    depends_on:
      php:
        condition: service_healthy
        restart: true

  php:
    container_name: php
    build:
      context: .docker/
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - .:/usr/local/apache2/htdocs
    networks:
      - php
    healthcheck:
      test: ["CMD", "php", "--version"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  db:
    image: mysql:8.0.43
    container_name: mysql
    restart: always
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE:  docker
      MYSQL_ROOT_PASSWORD: 657u65
    ports:
      - 3306:3306
    networks:
      - php
    healthcheck:
      test: ["CMD", "mysql"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    ports:
      - 3000:80
    networks:
      - php
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      db:
        condition: service_healthy
        restart: true

  adminer:
    image: adminer:5.3.0
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db:3306
      ADMINER_DESIGN: brade
    ports:
      - 3001:8080
    networks:
      - php
    depends_on:
      - db


volumes:
  mysql: {}

networks:
  php:
    driver: bridge
