name: php-environment

services:
  webserver:
    container_name: httpd
    build:
      context: .docker/
      dockerfile: apache.Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/usr/local/apache2/htdocs/
    networks:
      - php
    depends_on:
      php:
        condition: service_healthy
        restart: true

  php:
    container_name: php
    build:
      context: .docker/
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - .:/usr/local/apache2/htdocs/
    networks:
      - php
    healthcheck:
      test: ["CMD", "php", "--version"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    
# database:
#   restart: always

# phpmyadmin:
#   restart: always

volumes:
  database: {}
networks:
  php:
    driver: bridge
