services:
  websever:
    image: nginx:1.27-alpine3.21-slim
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - php_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php84
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - webserver
    networks:
      - php_network