services:
  webserver:
    image: nginx:1.29.1-alpine
    container_name: nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - skeleton

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - skeleton

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE:  docker
      MYSQL_ROOT_PASSWORD: 657u65
    ports:
      - 3306:3306
    networks:
      - skeleton
    healthcheck:
      test: ["CMD", "mysql"]
  adminer:
    image: adminer:5.3.0
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db:3306
      ADMINER_DESIGN: brade
    ports:
      - 3001:8080
    networks:
      - skeleton
    depends_on:
      - db

volumes:
  mysql: {}

networks:
  skeleton:
    name: skeleton
    driver: bridge
