#!/usr/bin/php

<?php
require __DIR__.'/vendor/autoload.php';

use app\commands\TesteCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

$application = new Application();

$application->add(new TesteCommand());

$application->run();